//------------------------------------------------------------------------------
// <auto-generated>
//     Manual changes may be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group19_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AccountGroup
    {
        public AccountGroup()
        {
            this.AccountGroup1 = new HashSet<AccountGroup>();
            this.MasterAccount = new HashSet<MasterAccount>();
        }

        // 📌 Unique identifier for the group
        public string ID { get; set; }

        // 📌 Group/Subgroup name
        public string Name { get; set; }

        // 📌 Optional ID of parent group (null = top-level group)
        public string ParentGroupID { get; set; }

        // 📌 Group type: Assets, Liabilities, Income, Expenses
        public string ElementType { get; set; } // Or rename to GroupElement for workbook consistency

        // 📌 Links this group to a specific user
        public string UserID { get; set; }

        // 🔗 Navigation properties for EF
        public virtual ICollection<AccountGroup> AccountGroup1 { get; set; } // Child groups
        public virtual AccountGroup AccountGroup2 { get; set; }              // Parent group
        public virtual ICollection<MasterAccount> MasterAccount { get; set; } // Linked master accounts
        public virtual UserPassword UserPassword { get; set; }                // Linked user
    }
}
