//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group19_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateHired { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
    
        public virtual UserPassword UserPassword { get; set; }
    }
}
