//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group19_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Required for Data Annotations

    public partial class MasterAccount
    {
        public MasterAccount()
        {
            this.TransactionLine = new HashSet<TransactionLine>();
        }

        // 📌 Unique account identifier: auto-generated in controller (e.g., USR123_ACC0001)
        [Key]
        public string ID { get; set; }

        // 📌 Name of the account (e.g., "Cash", "Utilities")
        [Required(ErrorMessage = "Account name is required.")]
        public string Name { get; set; }

        // 📌 Opening balance at account creation
        [Required(ErrorMessage = "Opening amount is required.")]
        [DataType(DataType.Currency)]
        public decimal OpeningAmount { get; set; }

        // 📌 Closing balance (calculated or manually updated)
        [Required(ErrorMessage = "Closing amount is required.")]
        [DataType(DataType.Currency)]
        public decimal ClosingAmount { get; set; }

        // 📌 Group this account belongs to (Assets, Expenses, etc.)
        [Required(ErrorMessage = "Please select a group.")]
        public string GroupID { get; set; }

        // 📌 User who owns the account
        public string UserID { get; set; }

        // 🔗 Navigation to account group
        public virtual AccountGroup AccountGroup { get; set; }

        // 🔗 Navigation to transactions
        public virtual ICollection<TransactionLine> TransactionLine { get; set; }

        // 🔗 Navigation to user
        public virtual UserPassword UserPassword { get; set; }
    }
}
