//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group19_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterAccount()
        {
            this.TransactionLine = new HashSet<TransactionLine>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public decimal OpeningAmount { get; set; }
        public decimal ClosingAmount { get; set; }
        public string GroupID { get; set; }
        public string UserID { get; set; }
    
        public virtual AccountGroup AccountGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLine> TransactionLine { get; set; }
        public virtual UserPassword UserPassword { get; set; }
    }
}
