//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group19_iFINANCEAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group19_iFINANCEDBEntities : DbContext
    {
        public Group19_iFINANCEDBEntities()
            : base("name=Group19_iFINANCEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountCategory> AccountCategory { get; set; }
        public virtual DbSet<AccountGroup> AccountGroup { get; set; }
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<MasterAccount> MasterAccount { get; set; }
        public virtual DbSet<NonAdminUser> NonAdminUser { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TransactionHeader> TransactionHeader { get; set; }
        public virtual DbSet<TransactionLine> TransactionLine { get; set; }
        public virtual DbSet<UserPassword> UserPassword { get; set; }
    }
}
