//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group19_iFINANCEAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLine
    {
        public string ID { get; set; }
        public string TransactionID { get; set; }
        public string AccountID { get; set; }
        public decimal CreditedAmount { get; set; }
        public decimal DebitedAmount { get; set; }
        public string Comments { get; set; }
    
        public virtual MasterAccount MasterAccount { get; set; }
        public virtual TransactionHeader TransactionHeader { get; set; }
    }
}
